// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwtwdiowjmqkljxovvdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3dHdkaW93am1xa2xqeG92dmRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1MDMxOTksImV4cCI6MjA4NDA3OTE5OX0.i2a3RW-eF2FOVKdMZlzJqW7IMirBcnHtgKxZiYDtbDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});