// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubfwpoppxqiynpxncemw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViZndwb3BweHFpeW5weG5jZW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzQ2NjAsImV4cCI6MjA2NDExMDY2MH0.wLyq_Lo2nDl0FIe1Ivh9RTTpaqrMA0zBF2AoJNOXo7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);